# Generated by Django 2.0.7 on 2018-08-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.CityDict', verbose_name='所在城市'),
        ),
    ]
