# Generated by Django 2.0.7 on 2018-08-16 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180816_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 23, 3, 45, 163894), verbose_name='过期时间'),
        ),
    ]
