# Generated by Django 2.0.7 on 2018-08-21 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180821_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 7, 48, 36, 576201), verbose_name='过期时间'),
        ),
    ]
